# version: '2'
#
# services:

  web:
    build: .
    environment:
      - MIX_ENV=dev # That's the environment mode, you know
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
      # - PG_PASSWORD=postgres
    ports:
      - 4000:4000
    links:
      - postgres

  postgres:
    image: postgres:9.5
    # environment:
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=app_dev
    ports:
      - 5432:5432
